// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkc6ht5h8zuHxcG4dOOl88f3lprJkTmF8',
    appId: '1:448421166474:web:cf9ac4c86e9828d4b41c73',
    messagingSenderId: '448421166474',
    projectId: 'testdb-ed9ce',
    authDomain: 'testdb-ed9ce.firebaseapp.com',
    databaseURL: 'https://testdb-ed9ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testdb-ed9ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKgE3-aAKeNZN68fX129RhSesGkNkU1U0',
    appId: '1:448421166474:android:36cf7621cd20308ab41c73',
    messagingSenderId: '448421166474',
    projectId: 'testdb-ed9ce',
    databaseURL: 'https://testdb-ed9ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testdb-ed9ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj9VqmSF9OkOgz_oHOvhyLw8HFan1VAE4',
    appId: '1:448421166474:ios:c2e8c13d7949dc09b41c73',
    messagingSenderId: '448421166474',
    projectId: 'testdb-ed9ce',
    databaseURL: 'https://testdb-ed9ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'testdb-ed9ce.appspot.com',
    iosClientId: '448421166474-riq8v8vonvfoeumbqermog09ecr39o9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.expensetracker',
  );
}
